const errorHandler = async (err, req, res, next) => {
  try {

  } catch (error) {

  }
}
module.exports = errorHandler